name: sheeps_app
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.1+9

environment:
  sdk: ">=2.9.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^4.0.0
  equatable: ^1.1.1
  flutter_svg: ^0.18.0
  http: ^0.12.2
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3
  rxdart: ^0.24.1
  intl: ^0.16.1 #DateTime Parsing
  badges: ^1.1.4 #알림에 사용할 Badge
  flutter_datetime_picker: ^1.4.0 #날짜 받아오기 위함
  provider: ^4.3.2+1 #provider

  firebase_messaging: ^6.0.16 #firebase
  firebase_auth: ^0.18.3
  firebase_core: ^0.5.2 #firebase

  adhara_socket_io: ^0.4.1 #소켓
  sqflite: ^1.3.1 #로컬 db
  path: ^1.7.0  #임시 디렉토리 가져옴
  path_provider: ^1.6.11  #getDocumentDirectory... 가져옴
  page_transition: ^1.1.6 #페이지 넘어갈때 action
  flutter_local_notifications: ^1.4.4+4 #폰 켜져있을 때 알림
  vibration: ^1.4.0 #진동
  image_picker: ^0.6.7+7 #카메라 라이브러리가져오는
  async: ^2.4.2 #firebase_auth_test.dart 파일에서 사용함 필요한지 확인 필요
  drag_and_drop_gridview: ^1.0.8 #사진 애니메이션
  extended_image: ^1.3.0 #서버에있는 이미지 받아옴
  fluttertoast: ^7.1.1 #toast ui
  flutter_keyboard_visibility: ^3.2.2 #키보드 보이는 용
  package_info: ^0.4.3+2 #패키지 정보 가져욤
  webview_flutter: 0.3.22+1 #웹뷰
  shared_preferences: ^0.5.1 #local 간단 db
  permission_handler: ^5.0.1+1 #권한 가져오기
  iamport_flutter: ^0.9.13 #본인인증
  dio: ^3.0.10 #form data 전송
  google_sign_in: ^4.5.6 #구글 로그인
  url_launcher: ^5.7.10 #웹뷰
  sign_in_with_apple: ^2.5.4 #애플 로그인
  flutter_easyloading: ^2.0.0 #로딩 ui
  custom_refresh_indicator: ^0.9.0 #scroll 상단 애니메이션
  cupertino_will_pop_scope: ^1.0.4 #ios willpop
de_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  assets:
    - assets/
    - assets/images/
    - assets/images/Badge/
    - assets/images/Badge/PersonalBadge/
    - assets/images/Badge/TeamBadge/
    - assets/images/Chat/
    - assets/images/Community/
    - assets/images/DashBoard/
    - assets/images/Global/
    - assets/images/LoginReg/
    - assets/images/NavigationBar/
    - assets/images/Profile/
    - assets/images/ProfileModify/
    - assets/images/Public/
    - assets/images/TotalNotification/
    - assets/txt/bannerFile.txt

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
